// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// bjimpute
Rcpp::NumericVector bjimpute(SEXP y, SEXP cen, SEXP x, SEXP inibeta);
RcppExport SEXP _SurvELM_bjimpute(SEXP ySEXP, SEXP cenSEXP, SEXP xSEXP, SEXP inibetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type cen(cenSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type inibeta(inibetaSEXP);
    rcpp_result_gen = Rcpp::wrap(bjimpute(y, cen, x, inibeta));
    return rcpp_result_gen;
END_RCPP
}
// mm_mult
arma::mat mm_mult(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _SurvELM_mm_mult(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(mm_mult(x, y));
    return rcpp_result_gen;
END_RCPP
}
// testDFtoNM
Rcpp::NumericMatrix testDFtoNM(DataFrame x);
RcppExport SEXP _SurvELM_testDFtoNM(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(testDFtoNM(x));
    return rcpp_result_gen;
END_RCPP
}
// scaleNM
Rcpp::List scaleNM(NumericMatrix x1);
RcppExport SEXP _SurvELM_scaleNM(SEXP x1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x1(x1SEXP);
    rcpp_result_gen = Rcpp::wrap(scaleNM(x1));
    return rcpp_result_gen;
END_RCPP
}
// kernmat
Rcpp::NumericMatrix kernmat(SEXP xtrain, SEXP kernel_type, SEXP kernel_para, SEXP xtest);
RcppExport SEXP _SurvELM_kernmat(SEXP xtrainSEXP, SEXP kernel_typeSEXP, SEXP kernel_paraSEXP, SEXP xtestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xtrain(xtrainSEXP);
    Rcpp::traits::input_parameter< SEXP >::type kernel_type(kernel_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type kernel_para(kernel_paraSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xtest(xtestSEXP);
    rcpp_result_gen = Rcpp::wrap(kernmat(xtrain, kernel_type, kernel_para, xtest));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurvELM_bjimpute", (DL_FUNC) &_SurvELM_bjimpute, 4},
    {"_SurvELM_mm_mult", (DL_FUNC) &_SurvELM_mm_mult, 2},
    {"_SurvELM_testDFtoNM", (DL_FUNC) &_SurvELM_testDFtoNM, 1},
    {"_SurvELM_scaleNM", (DL_FUNC) &_SurvELM_scaleNM, 1},
    {"_SurvELM_kernmat", (DL_FUNC) &_SurvELM_kernmat, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurvELM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
